config/routes.rb
Rails.application.routes.draw do

  root :to => redirect('/login')
  get "/login", to: "sessions#login"
  post "/login", to: "sessions#create"

  get "/sign_up", to: "students#new"
  post "/sign_up", to: "students#create", as: "students"

  get "/logout", to: "sessions#logout"
  
  get "/profile", to: "students#profile", as: "profile"
  get "/edit_profile", to: "students#edit_profile", as: "edit_profile"
  put "/edit_profile", to: "students#edit_profile", as: "edited_profile"

  get "/schedule", to: "schedules#index", as: "schedule"
  delete "/schedule", to: "schedules#destroy", as: "destroy_schedule"

  get "/add_course/:semester", to: "schedules#add_course", as: "add_course"
  post "/add_course/:semester", to: "schedules#create", as: "create_schedule"
  
  put "/schedule", to: "schedules#add_academic_year", as: "add_academic_year"
  post "/schedule", to: "schedules#delete_semester", as: "delete_semester"
  
  get "/all_courses/:semester", to: "schedules#all_courses", as: "all_courses_search"
  get "/all_courses/:semester", to: "schedules#all_courses", as: "all_courses"
  post "/all_courses/:semester", to: "schedules#create", as: "create_schedule_from_all"

end

app/models/student.rb
class Student < ActiveRecord::Base
  has_secure_password
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
 
	before_action :authorized, only: [:profile, :edit_profile]

	def new
        @major_minor_options = Major.all
        @school = [
			{ id: 1, name: 'Barnard College' },
			{ id: 2, name: 'Columbia College' },
			{ id: 3, name: 'SEAS' },
            { id: 4, name: 'GS' }
		]
		@student = Student.new
	end


	def create
		if Student.find_by_email(student_params[:email])
			flash[:notice] = "Email already exists!"
			redirect_to sign_up_path
		elsif Student.find_by_uni(student_params[:uni])
			flash[:notice] = "UNI already exists!"
			redirect_to sign_up_path
		else
			@student = Student.new(student_params)
			if !student_params[:email].empty? && @student.save
				#add default semesters
				Schedule.create(:uni => student_params[:uni], :semester => "Fall 2023")
				Schedule.create(:uni => student_params[:uni], :semester => "Spring 2024")
				flash[:notice] = "Profile created."
				redirect_to login_path
			else
				#flash[:notice] = " New Student: #{student_params}"
				# flash[:notice] = " Error Messages: #{@student.errors.messages}"
				flash[:notice] = "Error! Information incomplete!"
				redirect_to sign_up_path
			end
		end

	end

	def show #goes with view for profile page

	end

	# For profile pages
	def profile
		# id = params[:schedID] # retrieve schedID from URI route
		@student = Student.find(session[:student_id]) # look up schedule by unique ID
		# @major1 = Major.find(@student.major1).name
		# @major1 = @student.major1 ? Major.find(@student.major1).name : ""
		if @student.major1.present?
			@major1 = Major.find(@student.major1).name
		# else
		# 	@major1 = "" 
		end
		if @student.major2.present?
			@major2 = Major.find(@student.major2).name
		else
			@major2 = ""  
		end
		if @student.minor1.present?
			@minor1 = Major.find(@student.minor1).name
		else
			@minor1 = ""  
		end
		if @student.minor2.present?
			@minor2 = Major.find(@student.minor2).name
		else
			@minor2 = ""  
		end
		if @student.minor3.present?
			@minor3 = Major.find(@student.minor3).name
		else
			@minor3 = ""  
		end
		
	end
   
	def edit_profile
		@student = Student.find(session[:student_id])
		@categories = [
			{ id: 1, name: 'Fall 2021' },
			{ id: 2, name: 'Spring 2022' },
			{ id: 3, name: 'Summer 2022' },
			{ id: 4, name: 'Fall 2022' },
			{ id: 5, name: 'Spring 2023' },
			{ id: 6, name: 'Summer 2023' },
			{ id: 7, name: 'Fall 2023' },
			{ id: 8, name: 'Spring 2024' },
			{ id: 9, name: 'Summer 2024' },
			{ id: 10, name: 'Fall 2024' },
			{ id: 11, name: 'Spring 2025' },
			{ id: 12, name: 'Summer 2025' },
			{ id: 13, name: 'Fall 2025' },
			{ id: 14, name: 'Spring 2026' },
			{ id: 15, name: 'Summer 2026' },
		]
		@season = [
			{ id: 1, name: 'Fall' },
			{ id: 2, name: 'Spring' },
			{ id: 3, name: 'Summer' }
		]
		@year = [
			{ id: 1, name: '2017' },
			{ id: 2, name: '2018' },
			{ id: 3, name: '2019' },
			{ id: 4, name: '2020' },
			{ id: 5, name: '2021' },
			{ id: 6, name: '2022' },
			{ id: 7, name: '2023' },
			{ id: 8, name: '2024' },
			{ id: 9, name: '2025' },
			{ id: 10, name: '2026' },
			{ id: 11, name: '2027' },
			{ id: 12, name: '2028' }
		]
		@major_minor_options = Major.all
		if request.put?
		  if @student.update(student_params)
			flash[:notice] = "Profile was successfully updated."
			puts @student.standing
			redirect_to profile_path
		  else
			flash[:error] = "Error updating profile."
			render :edit_profile
		  end
		end
	end
	  
	private
	
	def student_params
		params.require(:student).permit(:uni, :email, :firstName, :lastName, :standing, :major1, :major2, :minor1, :minor2, :minor3, :password)
	end
end

app/views/students/edit_profile.html.erb
<h1 class="page-title"> Edit Profile </h1>

<h3 class="profile-name" style="font-size: 20pt">Name: <%=@student.firstName%> <%=@student.lastName %></h3>
<!--
<%= form_for @student, url: edited_profile_path, method: :put do |f| %>
  <%= label :student, :standing, 'Standing', :class => 'col-form-label' %>
  <%= text_field :student, 'standing', :class => 'form-control' %>
  <%= label :student, :major1, 'Major 1', :class => 'col-form-label' %>
  <%= text_field :student, 'major1', :class => 'form-control' %>
  <%= label :student, :major2, 'Major 2', :class => 'col-form-label'  %>
  <%= text_field :student, 'major2', :class => 'form-control' %>
  <%= label :student, :minor1, 'Minor 1', :class => 'col-form-label'  %>
  <%= text_field :student, 'minor1', :class => 'form-control' %>
  <%= label :student, :minor2, 'Minor 2', :class => 'col-form-label'  %>
  <%= text_field :student, 'minor2', :class => 'form-control' %>
  <%= label :student, :minor3, 'Minor 3', :class => 'col-form-label'  %>
  <%= text_field :student, 'minor3', :class => 'form-control' %>
  <br/>
  <%= submit_tag 'Update Profile', :class => 'btn btn-primary' %>
  <%= link_to 'Cancel', profile_path, :class => 'btn btn-secondary' %>
<% end %>
-->
<div style="text-align: center">
<%= form_for @student, url: edited_profile_path, method: :put do |f| %>
  <%= label :student, :standing, 'Standing: ', :class => 'col-form-label profile-name md-font-size' %>
  <select name='student[standing]' id="Standing">
    <% @categories.each do |category| %>
      <option value="<%= category[:name] %>"><%= category[:name] %></option>
    <% end %>
  </select>
  <br>

  <%= label :student, :major1, 'Major: ', :class => 'col-form-label profile-name md-font-size' %>
  <select name='student[major1]' id="Major">
    <% @major_minor_options.each do |major| %>
      <option value="<%= major[:id] %>"><%= major[:name] %></option>
    <% end %>
  </select>
  <br>
  <br/>
  <div class="profile-button d-flex justify-content-center">
    <div class="profile-button">
      <%= submit_tag 'Update Profile', :class => 'btn btn-primary profile-back' %>
    </div>
    <div class="profile-button">
      <%= link_to 'Cancel', profile_path, :class => 'btn btn-secondary profile-edit' %>
    </div>
  </div>
<% end %>

</div>

app/views/students/login.html.erb
<h1> Login <h1>


<%= form_tag schedule_path(@schedule), :method => :post do %>
  <%= label :student, :email, 'email', :class => 'col-form-label' %>
  <%= text_field :student, 'email', :class => 'form-control' %>
  <%= label :student, :password, 'password', :class => 'col-form-label' %>
  <%= text_field :student, 'password', :class => 'form-control' %>
  <br/>
  <%= submit_tag 'Login', :class => 'btn btn-primary' %>
  <%= link_to 'Cancel', login_path, :class => 'btn btn-secondary' %>
<% end %>

app/views/students/new.html.erb
<h1 class="page-title"> Sign Up <h1>


<%= form_for(@student) do |f| %>
  <div class="form-group">
    <%= f.label :firstName, 'First Name', :class => 'col-form-label profile-name md-font-size' %>
    <%= f.text_field :firstName, class: 'form-control small-input'  %>
  </div>
  <div class="form-group">
    <%= f.label :lastName, 'Last Name', :class => 'col-form-label profile-name md-font-size' %>
    <%= f.text_field :lastName, class: 'form-control small-input'  %>
  </div>
  <div class="form-group">
    <%= f.label :uni, 'uni', :class => 'col-form-label profile-name md-font-size' %>
    <%= f.text_field :uni, class: 'form-control small-input'  %>
  </div>

  <div class="form-group">
    <%= f.label :school, 'school', :class => 'col-form-label profile-name md-font-size' %>
    <select name='student[school]' id="School" class= 'form-control small-input'>
      <% @school.each do |school| %>
        <option value="<%= school[:id] %>"><%= school[:name] %></option>
      <% end %>
    </select>
  </div>  

  <div class="form-group">
    <%= f.label :major1, 'major', :class => 'col-form-label profile-name md-font-size' %>
    <select name='student[major1]' id="Major 1" class= 'form-control small-input'>
      <% @major_minor_options.each do |major| %>
        <option value="<%= major[:id] %>"><%= major[:name] %></option>
      <% end %>
    </select>
  </div>  
  <div class="form-group">
    <%= f.label :email, 'email', :class => 'col-form-label profile-name md-font-size' %>
    <%= f.text_field :email, class: 'form-control small-input'  %>
  </div>
  <div class="form-group">
    <%= f.label :password, 'password', :class => 'col-form-label profile-name md-font-size' %>
    <%= f.password_field :password, class: 'form-control small-input'  %>
  </div>
  <br/>
  <div class="profile-button d-flex justify-content-center">
    <div class="profile-button">
        <%= submit_tag 'Sign Up', :class => 'btn btn-primary profile-back' %>
    </div>
    <div class="profile-button">
        <%= link_to 'Cancel', login_path, :class => 'btn btn-secondary profile-edit' %>
    </div>
  </div>
  
<% end %>

<div style="margin: 50px"></div>

app/views/students/profile.html.erb
<!--  app/views/schedules/profile.html.erb -->
<h1 class="page-title"> Profile </h1>

<ul id="profile" style="list-style-type: none" class="profile-body">
  <li class="profile-name">
    <!-- Name: -->
    <%= @student.firstName%> <%=@student.lastName %>
  </li>
  <li>
    <!-- Uni: -->
        <%= @student.uni %>
  </li>
  <li>
    <!-- Standing: -->
        <%= @student.standing %>
  </li>
</ul>
<br>
<div class="d-flex justify-content-center">
  <table class="table major-table table col-md-4">
    <tbody>
      <tr>
        <th >Major:</th>
        <td><%= @major1 %></td>
      </tr>
    </tbody>
  </table>

</div>

<br>

<!-- <h3>Links:</h3> -->

<div class="profile-button d-flex justify-content-center">
  <div class="profile-button">
    <%= link_to 'Edit Profile', edit_profile_path, :class => 'btn btn-secondary profile-edit' %>
  </div>
  <div class="profile-button">
    <%= link_to 'Back to Schedules', schedule_path, :class => 'btn btn-primary profile-back' %>
  </div>
</div>