config/routes.rb
Rails.application.routes.draw do

  root :to => redirect('/login')
  get "/login", to: "sessions#login"
  post "/login", to: "sessions#create"

  get "/sign_up", to: "students#new"
  post "/sign_up", to: "students#create", as: "students"

  get "/logout", to: "sessions#logout"
  
  get "/profile", to: "students#profile", as: "profile"
  get "/edit_profile", to: "students#edit_profile", as: "edit_profile"
  put "/edit_profile", to: "students#edit_profile", as: "edited_profile"

  get "/schedule", to: "schedules#index", as: "schedule"
  delete "/schedule", to: "schedules#destroy", as: "destroy_schedule"

  get "/add_course/:semester", to: "schedules#add_course", as: "add_course"
  post "/add_course/:semester", to: "schedules#create", as: "create_schedule"
  
  put "/schedule", to: "schedules#add_academic_year", as: "add_academic_year"
  post "/schedule", to: "schedules#delete_semester", as: "delete_semester"
  
  get "/all_courses/:semester", to: "schedules#all_courses", as: "all_courses_search"
  get "/all_courses/:semester", to: "schedules#all_courses", as: "all_courses"
  post "/all_courses/:semester", to: "schedules#create", as: "create_schedule_from_all"

end

app/models/schedule.rb
class Schedule < ActiveRecord::Base
	belongs_to :course, :foreign_key => "courseID"
	belongs_to :requirement, :foreign_key => "reqID"
	def self.get_full_schedule()
		#Schedule.joins(:course).select("schedules.* ,courses.*")
		#Schedule.includes(:course)
		#Schedule.joins(:course).includes(:requirement).select("schedules.* ,courses.*, requirements.*")
		Schedule.joins(:course, :requirement).select("schedules.* ,courses.*, requirements.*")
		#Schedule.joins("INNER JOIN courses ON schedules.courseID = courses.courseID").select("schedules.*, courses.*")
		#Schedule.joins("INNER JOIN courses ON schedules.courseID = courses.courseID
		#LEFT OUTER JOIN requirements ON schedules.reqID = requirements.reqID;")
		#Schedule.includes(:course, :requirement).where.not(courses: { courseID: nil }).select("schedules.* ,courses.courseTitle as courseTitle, requirements.reqLabel as reqLabel")
		#all = Schedule.joins(:course).select("schedules.semester, schedules.reqID, courses.courseTitle, courses.prefixCode, courses.courseCode").includes(:requirement).select("requirement.*")
		#Schedule.joins(:course).includes(:requirement).select(:semester, :reqID, :courseTitle, :prefixCode, :courseCode, :reqLabel)
		#schedules = Schedule.joins(:course).select(:semester, :reqID, :courseTitle, :prefixCode, :courseCode)
		#schedules.each do |schedule|
			# Fetch requirements separately for each schedule
		#	myreq = Requirement.where(reqID: schedule.reqID).select('reqLabel')
			# Assign fetched requirements to the schedule
		#	if (myreq)
		#		schedule.reqLabel = myreq
		#	else
		#		schedule.reqLabel = nil
			#schedule.reqLabel = myreq.reqLabel if requirements.any?
		#	end
		#end

		#Schedule.includes(:requirement).select("schedules.*, requirement.*")
		#Schedule.find_by_sql("SELECT * from schedules 
		#INNER JOIN courses ON schedules.courseID = courses.courseID
		#LEFT OUTER JOIN requirements ON schedules.reqID = requirements.reqID;")

		#Schedule.joins(:course).includes(:requirement).select("schedules.* ,courses.*, requirements.*")
	end
	def self.get_semesters()
		Schedule.where(course: nil)
	end
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController

  before_action :authorized, only: [:index, :add_course, :all_courses]

  def index
    @majorID = (Student.find_by_id(session[:student_id])).major1 
    @uni = (Student.find_by_id(session[:student_id])).uni
    @major = Major.find_by_major_minorID(@majorID)
    @major_name = @majorID ? @major.name : ""
    @schedule = Schedule.get_full_schedule().where(uni: @uni) #schedule specific to student

    #display options for semesters to add
    @years = [2020, 2021, 2022, 2023, 2024, 2025]
    @options = []
    @years.each {|i| @options.append({:season => 'Fall', :year => i.to_s}) && @options.append({:season => 'Spring', :year => (i+1).to_s})}

    @req_labels = Requirement.get_requirement_labels_by_major(@major)
    #retrieve semesters from db and put in academic_year dictionary
    @semesters = Schedule.distinct.where(uni: @uni).pluck(:semester) #array
    #@semesters = Schedule.get_semesters().where(uni: @uni)

    @ay_hash = Hash.new { |h,k| h[k] = [] }

    #find the academic year for the semester
    for sem in @semesters do
      @season = sem.split(" ")[0]
      @year = sem.split(" ")[1].to_i
      if (@season == "Fall")
        @ay = @year
      else
        @ay = @year - 1
      end

      #add the semester to the academic year hash
      @ay_name = @ay.to_s + " - " + (@ay + 1).to_s
      @ay_hash[@ay_name] << sem
    end

    #sort chronologically
    @ay_hash = @ay_hash.transform_values { |value| value.sort }
    @ay_hash = @ay_hash.sort_by { |key| key }.to_h

  end


  def add_course
    @uni = (Student.find_by_id(session[:student_id])).uni
    @semester = params[:semester]
    @major = (Student.find_by_id(session[:student_id])).major1
    @requirements = Requirement.get_requirements_by_major(@major)
    @courses_to_fulfill = {} #hash of requirements and courses to fulfill
    @requirements.each {|i| @courses_to_fulfill[i]=(Course.get_courses_by_requirement(i))}
  end

  def all_courses
    @uni = (Student.find_by_id(session[:student_id])).uni
    @semester = params[:semester]
    @courses = Course.paginate(page: params[:page])

    if params[:search_by_course_code].present?
      @courses = @courses.where(:courseCode => 
      params[:search_by_course_code]).paginate(page: params[:page])
    end
    if params[:search_by_course_name].present?
      #@courses = @courses.where(params[:search_by_course_name].match(:courseTitle)).paginate(page: params[:page])
      # Create an Arel table for the Course model
      courses_table = @courses.arel_table

      # Create an Arel predicate for case-insensitive matching of the search term within the courseTitle column
      search_predicate = courses_table[:courseTitle].matches("%#{params[:search_by_course_name]}%")

      # Use the Arel predicate in the where clause with ILIKE for PostgreSQL
      @courses = @courses.where(search_predicate).paginate(page: params[:page])
    end

    if params[:sort_by].present?
      if params[:sort_by] == "courseCode"
        @courses = @courses.order(:courseCode)
      end
      if params[:sort_by] == "courseTitle"
        @courses = @courses.order(:courseTitle)
      end
    end

  end


  def add_academic_year

    @sem = params[:year]
    @uni = (Student.find_by_id(session[:student_id])).uni

    #check if semester is already added. if no, add
    @mysem = Schedule.get_semesters().where(uni: @uni, semester: @sem)[0]

    if @mysem
      flash[:notice] = "Semester '#{@mysem.semester}' already added."
    else
      Schedule.create(:uni => @uni, :semester => @sem)
    end

    redirect_to schedule_path
  end


  def create
    @uni = (Student.find_by_id(session[:student_id])).uni
    @my_courses = Schedule.where(uni: @uni)
    @course_ids = @my_courses.pluck(:courseID).map(&:to_s)
    @course_id_to_check = schedule_params[:courseID].to_s
    if @course_ids.include?(@course_id_to_check)
      flash[:notice] = "Course '#{Course.find(@course_id_to_check).courseTitle}' already added."
      redirect_to add_course_path
    else
      #if from all-courses page, check if it fulfills a major req. if yes, change the schedule_params
      # if (schedule_params[:reqID] == 1)
      #   req = Coursereqs.where(courseID == schedule_params[:courseID])
      #   if(req)
      #     schedule_params[:reqID] = req.first.reqID
      #   end
      # end
      @schedule = Schedule.create!(schedule_params)
      flash[:notice] = "Course #{Course.find(schedule_params[:courseID]).courseTitle} was successfully added."
      redirect_to schedule_path
    end
  end

  def destroy
    @id = params[:schedID]
    @schedule = Schedule.find(@id)
    @course_id = @schedule.courseID
    @schedule.destroy
    flash[:notice] = "Course '#{Course.find(@course_id).courseTitle}' deleted."
    redirect_to schedule_path
  end

  def delete_semester
    @uni = (Student.find_by_id(session[:student_id])).uni
    @semester = params[:semester]
    @schedule = Schedule.get_full_schedule().where(uni: @uni).where(semester: @semester)
    

    @schedule.each do |course| 
      @course_to_delete = Schedule.find(course.id)
      @course_to_delete.destroy
    end

    @semester_to_delete = Schedule.get_semesters().where(uni: @uni, semester: @semester)[0]
    @semester_to_delete.destroy

    redirect_to schedule_path

  end



  private
  # Making "internal" methods private is not required, but is a common practice.
  # This helps make clear which methods respond to requests, and which ones do not.
  def schedule_params
    params.require(:schedule).permit(:schedID, :uni, :courseID, :semester, :reqID, :taken)
  end

end

app/views/schedules/add_course.html.erb
<!--Find me in app/views/courses/add_course.html.erb-->
<h1 class="page-title"> Add Course </h1>

<h2 class="profile-name"> Requirements for <em><%= @semester %></em></h2> 

<button class="float-right m-4 back-button"> <%= link_to "All Courses ->", all_courses_path(semester: @semester) %> </button>
<table class="table table-striped col-md-12" id="courses">
    <tr id = "test" class="body-text">
      <th>Course</th>
      <th>Course Code</th>
      <th>Action</th>
    </tr>
    <% @courses_to_fulfill.each do |req, courses| %>
        <tr>
          <td class="req">
            <%= req.reqLabel %>
          </td>
        </tr>
        <% courses.each do |course| %>
          <tr id="<%= course.courseTitle %>">
            <td class="course">
              <%= course.courseTitle %>
            </td>
            <td class="course">
            <%= course.prefixCode + " " + course.courseCode %>
          </td>
            <td class="course">
              <%= button_to "add", { schedule: { uni: @uni, courseID: course.courseID, semester: params[:semester], reqID: req.reqID, id: course.courseID }, id: course.courseID }, class: 'add-button' %>
            </td>
          </tr>
        <% end %>
    <% end %>
</table>

app/views/schedules/all_courses.html.erb
<h1 class="page-title"> All Courses </h1>

<h2 class="profile-name"><em><%= @semester %></em></h2>
<%= form_tag all_courses_search_path, method: "GET" do %>

  <div class="form-row">
    <div class="form-group col-md-6">
      <%= label_tag "Search by course name", nil, class: 'col-form-label profile-name md-font-size' %>
      <%= text_field_tag :search_by_course_name, params[:search_by_course_name], class: 'form-control small-input' %>
    </div>

    <div class="form-group col-md-6">
      <%= label_tag "Search by course code", nil, class: 'col-form-label profile-name md-font-size' %>
      <%= text_field_tag :search_by_course_code, params[:search_by_course_code], class: 'form-control small-input' %>
    </div>
  </div>

  <button id="searchButton", class="search-button">
      <%= submit_tag "Search", :class => 'btn btn-primary profile-back'%>
  </button>

<% end %>
<button class="float-left m-4 back-button"> 
  <%= link_to "<- Add Course by Requirement", add_course_path(semester: @semester) %> 
</button>

<table class="table table-striped col-md-12" id="courses">
    <tr id = "test" class="body-text">
    <th>
      <%= link_to 'Course', all_courses_search_path({sort_by: "courseTitle", search_by_course_name: params[:search_by_course_name], search_by_course_code: params[:search_by_course_code]}), id: 'courseTitle_header', class: ('bg-warning hilite' if @sort_by == 'courseTitle') %>
    </th>
    <th>
      <%= link_to 'Course Code', all_courses_search_path({sort_by: "courseCode", search_by_course_name: params[:search_by_course_name], search_by_course_code: params[:search_by_course_code]}), id: 'courseCode_header', class: ('bg-warning hilite' if @sort_by == 'courseCode') %>
    </th>
      <th>Action</th>
    </tr>
    <% @courses.each do |course| %>
          <tr>
            <td class="course">
              <%= course.courseTitle %>
            </td>
        <td class="course">
        <%= course.prefixCode + " "+ course.courseCode %>
        </td>
            <td class="course">
              <%= button_to "add", { schedule: { uni: @uni, courseID: course.courseID, semester: params[:semester], reqID: 1, id: course.courseID }}, class: 'add-button' %>
            </td>
          </tr>
    <% end %>
</table>


<%= will_paginate @courses, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>

app/views/schedules/index.html.erb
<!--Find me in app/views/courses/index.html.erb -->
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style>
    .dropbtn {
        color: white;
        padding: 16px;
        font-size: 16px;
        border: none;
    }

    .dropdown {
        position: relative;
        display: inline-block;
    }

    .dropdown-content a {
        display: none;
        position: absolute;
        background-color: #f1f1f1;
        min-width: 160px;
        box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
        z-index: 1;
    }

    .dropdown-content a {
        color: black;
        padding: 12px 16px;
        text-decoration: none;
        display: block;
    }

    .dropdown-content a:hover {background-color: #ddd;}
    .dropdown:hover .dropdown-content {display: block;}
    .dropdown:hover .dropbtn {background-color: #3e8e41;}
    </style>
</head>

<h1 class="page-title">My Courses</h1>

<br>

<%= form_tag add_academic_year_path, :method => :put do %>
  <div style="margin-left: auto;">
    <label for="year">Select Semester:</label>
    <select name="year" id="Year">
      <% @options.each do |option| %>
        <option value="<%= option[:season] + " " + option[:year] %>"><%= option[:season] + " " + option[:year] %></option>
      <% end %>
    </select>
    <button id="myButton" class="add-academic-year-button">
      <%= submit_tag "Add Semester", :class => 'btn btn-primary profile-back'%>
    </button>
  </div>
<% end %>


<div class="">

    <% @ay_hash.each do |year, semesters| %>
    <br />
    <h3 class="a-year-title" style="margin: 0;"><%= year %></h3>
      <div class="d-flex justify-content-between">
      <% semesters.each do |semester| %>
      <table class="table semester-table col-md-6" id="<%= semester %>">
        <thead>
          
          <tr>
            <th colspan="5" style="text-align: left; border: none;">
              <div class="table-title">
                <div>
                  <h3 class="sem-title" style="margin: 0;"><%= semester %></h3>
                </div>
                <div style="margin-left: auto;">
                  <button id="myButton" class="add-semester-button">
                    <%= link_to "Add Courses", add_course_path(semester: semester) %>
                  </button>
                </div>
                <div style="margin-left: auto;">
                <button id="myButton" class="delete-semester-button">
                  <%= button_to "Delete Semester",  delete_semester_path(semester: semester) %>
                </button>
                </div>
              </div>
            </th>
          </tr>
          
          <tr class="body-text">
            <th>Course</th>
            <th>Course Code</th>
            <th>Requirements</th>
            <th>Action</th>
          </tr>

        </thead>
        <tbody class="body-text">
          <% @schedule.each do |course| %>
              <% if course.semester == semester %>
                <tr id="<%= course.courseTitle %>">
                  <!-- <td>
                    <%= course.semester %>
                  </td> -->
                  <td>
                    <%= course.courseTitle %>
                  </td>
                  <td class="course">
                  <%= course.prefixCode + " " + course.courseCode %>
                  </td>
                  <td>
                    <% if @req_labels.include?(course.reqLabel) %>
                      <%= course.reqLabel ? course.reqLabel : "" %>
                    <% end %>
                  </td>
                  <td> 
                        <%= button_to "delete", destroy_schedule_path(:schedID => course.schedID), method: :delete, :schedID => course.schedID, class: 'delete-button' %>
                  </td>
                </tr>
              <% end %>
          <% end %>
        </tbody>
      </table>
      <% end %>
      </div>
    <% end %>
</div>