config/routes.rb
Rails.application.routes.draw do

  root :to => redirect('/login')
  get "/login", to: "sessions#login"
  post "/login", to: "sessions#create"

  get "/sign_up", to: "students#new"
  post "/sign_up", to: "students#create", as: "students"

  get "/logout", to: "sessions#logout"
  
  get "/profile", to: "students#profile", as: "profile"
  get "/edit_profile", to: "students#edit_profile", as: "edit_profile"
  put "/edit_profile", to: "students#edit_profile", as: "edited_profile"

  get "/schedule", to: "schedules#index", as: "schedule"
  delete "/schedule", to: "schedules#destroy", as: "destroy_schedule"

  get "/add_course/:semester", to: "schedules#add_course", as: "add_course"
  post "/add_course/:semester", to: "schedules#create", as: "create_schedule"
  
  put "/schedule", to: "schedules#add_academic_year", as: "add_academic_year"
  post "/schedule", to: "schedules#delete_semester", as: "delete_semester"
  
  get "/all_courses/:semester", to: "schedules#all_courses", as: "all_courses_search"
  get "/all_courses/:semester", to: "schedules#all_courses", as: "all_courses"
  post "/all_courses/:semester", to: "schedules#create", as: "create_schedule_from_all"

end

app/views/layouts/_flash.erb
<% if flash[:notice] %>
  <div class="alert alert-info" role="alert" id="notice">
    <%= flash[:notice] %>
  </div>
<% elsif flash[:warning] %>
  <div class="alert alert-danger" role="alert" id="warning">
    <%= flash[:warning] %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<%# Our "base" layout should be a valid HTML document. %>
<!DOCTYPE html>
<html>
  <head>
    <title>CUTomorrow</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', 'media' => 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>

      <%# These classes come from the Bootstrap CSS framework. %>
      <nav class="navbar navbar-expand-lg bg-white mb-3">
        <%= image_tag('logo.png', alt: 'CUTomorrow', class: 'scaled-image') %>
        <!-- <h1 class="title">CUTomorrow!</h1> -->
          <div style="margin-left: auto;">
            <button class="nav-button" ><%= link_to 'Schedules', schedule_path%></button>
            <button class="nav-button" ><%= link_to "Profile", profile_path %></button>
            <button class="nav-button" ><%= link_to "Logout", logout_path %></button>
          </div>
      </nav>

      <div class="container">
        <%# Render "flash" messages in our application. This loads _flash.erb %>
        <%= render 'layouts/flash' %>
        <main id="main">
          <%= yield %>
        </main>
      </div>
  </body>
</html>